import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ApplyBanner from "@/components/ApplyBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Header />
        </div>
        <div>
          {children}
        </div>
        {/* <ApplyBanner /> */}
      </body>
    </html>
  );
}
